apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: enterprise
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Enterprise Advanced App — production workloads
  sourceRepos:
    - "*"
  destinations:
    - namespace: enterprise-app
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  orphanedResources:
    warn: true
